/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.umg.proyectofinalboletos.view;

/**
 *
 * @author MK
 * 
 */

import java.awt.Color;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import com.umg.proyectofinalboletos.model.*;
import com.umg.proyectofinalboletos.service.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

public class Sales_Details_View extends javax.swing.JInternalFrame {
    
    private Sales_DetailsService service = new Sales_DetailsService();

    private final JPanel[] paneles;
    String[] columnas = {"ID", "ID Venta", "ID Localidad", "ID Partido", "ID Inventario", "Cantidad", "Precio Unitario"};
    DefaultTableModel modelo = new DefaultTableModel(null, columnas);
    public Sales_Details_View() {
        Sales_Details_View data;
        initComponents();
        updateTable();
        this.setBorder(null);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        tbl.setModel(modelo);
        jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        tbl.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            @Override
            public void  valueChanged (ListSelectionEvent e){
                fillFieldsFromSelectedRow();
            }
        });
        txtId.setEnabled(true);

            cleanCampos();
        
    // <editor-fold defaultstate="collapsed" desc="Configuraciones de Botones">
    paneles = new JPanel[] { btnCrear, btnBuscar, btnActualizar, btnEliminar, btnLimpiar, btnMostrarTodos }; 
    Color colorNormal = new Color(65,108,64);  
    Color colorHover = new Color(98,167,97);   

        for (JPanel panel : paneles) {
            panel.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                    panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                    panel.setBackground(colorHover);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                    panel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                    panel.setBackground(colorNormal);
            }
            });

        }
    // </editor-fold>
    }

    private void fillFieldsFromSelectedRow() {
        int row = tbl.getSelectedRow();
        if (row != -1) {
            int id = (int) modelo.getValueAt(row, 0);
            txtId.setText(String.valueOf(id));
            txtIdSale.setText(String.valueOf(modelo.getValueAt(row, 1)));
            txtIdPlace.setText(String.valueOf(modelo.getValueAt(row, 2)));
            txtIdMatch.setText(String.valueOf(modelo.getValueAt(row, 3)));
            txtIdInventory.setText(String.valueOf(modelo.getValueAt(row, 4)));
            txtQuanti.setText(String.valueOf(modelo.getValueAt(row, 5)));
            txtPrice.setText(String.valueOf(modelo.getValueAt(row, 6)));
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtIdSale = new javax.swing.JTextField();
        txtIdPlace = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        btnCrear = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnMostrarTodos = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtIdMatch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        txtQuanti = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdInventory = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();

        setMaximumSize(new java.awt.Dimension(1042, 776));
        setMinimumSize(new java.awt.Dimension(1042, 776));
        setPreferredSize(new java.awt.Dimension(1042, 776));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setMaximumSize(new java.awt.Dimension(1030, 740));
        background.setMinimumSize(new java.awt.Dimension(1030, 740));
        background.setPreferredSize(new java.awt.Dimension(1030, 740));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("ID:");
        jLabel10.setMaximumSize(new java.awt.Dimension(101, 15));
        jLabel10.setMinimumSize(new java.awt.Dimension(101, 15));
        jLabel10.setPreferredSize(new java.awt.Dimension(101, 15));
        background.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("ID de Venta:");
        jLabel1.setMaximumSize(new java.awt.Dimension(101, 15));
        jLabel1.setMinimumSize(new java.awt.Dimension(101, 15));
        jLabel1.setPreferredSize(new java.awt.Dimension(101, 15));
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("ID de Localidad:");
        jLabel2.setMaximumSize(new java.awt.Dimension(101, 15));
        jLabel2.setMinimumSize(new java.awt.Dimension(101, 15));
        jLabel2.setPreferredSize(new java.awt.Dimension(101, 15));
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        txtId.setBackground(new java.awt.Color(255, 255, 255));
        txtId.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtId.setBorder(null);
        txtId.setMinimumSize(new java.awt.Dimension(300, 26));
        txtId.setPreferredSize(new java.awt.Dimension(300, 26));
        background.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        txtIdSale.setBackground(new java.awt.Color(255, 255, 255));
        txtIdSale.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtIdSale.setBorder(null);
        txtIdSale.setMinimumSize(new java.awt.Dimension(300, 26));
        txtIdSale.setPreferredSize(new java.awt.Dimension(300, 26));
        background.add(txtIdSale, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        txtIdPlace.setBackground(new java.awt.Color(255, 255, 255));
        txtIdPlace.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtIdPlace.setBorder(null);
        txtIdPlace.setMinimumSize(new java.awt.Dimension(300, 26));
        txtIdPlace.setPreferredSize(new java.awt.Dimension(300, 26));
        background.add(txtIdPlace, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        jScrollPane1.setBorder(null);

        tbl.setBackground(new java.awt.Color(255, 255, 255));
        tbl.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {}
        ));
        tbl.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        tbl.setFocusable(false);
        jScrollPane1.setViewportView(tbl);

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 20, 550, 700));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setMaximumSize(new java.awt.Dimension(300, 10));
        jSeparator3.setMinimumSize(new java.awt.Dimension(300, 10));
        jSeparator3.setPreferredSize(new java.awt.Dimension(300, 10));
        background.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator5.setMaximumSize(new java.awt.Dimension(300, 10));
        jSeparator5.setMinimumSize(new java.awt.Dimension(300, 10));
        jSeparator5.setPreferredSize(new java.awt.Dimension(300, 10));
        background.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        jSeparator6.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator6.setMaximumSize(new java.awt.Dimension(300, 10));
        jSeparator6.setMinimumSize(new java.awt.Dimension(300, 10));
        jSeparator6.setPreferredSize(new java.awt.Dimension(300, 10));
        background.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        jSeparator12.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator12.setMaximumSize(new java.awt.Dimension(1010, 11));
        jSeparator12.setMinimumSize(new java.awt.Dimension(1010, 11));
        jSeparator12.setPreferredSize(new java.awt.Dimension(1010, 11));
        background.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 10, 710));

        btnCrear.setBackground(new java.awt.Color(65, 108, 64));
        btnCrear.setMaximumSize(new java.awt.Dimension(140, 40));
        btnCrear.setMinimumSize(new java.awt.Dimension(140, 40));
        btnCrear.setPreferredSize(new java.awt.Dimension(140, 40));
        btnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Agregar");

        javax.swing.GroupLayout btnCrearLayout = new javax.swing.GroupLayout(btnCrear);
        btnCrear.setLayout(btnCrearLayout);
        btnCrearLayout.setHorizontalGroup(
            btnCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCrearLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel11))
        );
        btnCrearLayout.setVerticalGroup(
            btnCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCrearLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel11))
        );

        background.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 340, -1, -1));

        btnActualizar.setBackground(new java.awt.Color(65, 108, 64));
        btnActualizar.setMaximumSize(new java.awt.Dimension(140, 40));
        btnActualizar.setMinimumSize(new java.awt.Dimension(140, 40));
        btnActualizar.setPreferredSize(new java.awt.Dimension(140, 40));
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Actualizar");

        javax.swing.GroupLayout btnActualizarLayout = new javax.swing.GroupLayout(btnActualizar);
        btnActualizar.setLayout(btnActualizarLayout);
        btnActualizarLayout.setHorizontalGroup(
            btnActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnActualizarLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel12))
        );
        btnActualizarLayout.setVerticalGroup(
            btnActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnActualizarLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel12))
        );

        background.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 490, -1, -1));

        btnBuscar.setBackground(new java.awt.Color(65, 108, 64));
        btnBuscar.setMaximumSize(new java.awt.Dimension(140, 40));
        btnBuscar.setMinimumSize(new java.awt.Dimension(140, 40));
        btnBuscar.setPreferredSize(new java.awt.Dimension(140, 40));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Buscar");

        javax.swing.GroupLayout btnBuscarLayout = new javax.swing.GroupLayout(btnBuscar);
        btnBuscar.setLayout(btnBuscarLayout);
        btnBuscarLayout.setHorizontalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBuscarLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel13))
        );
        btnBuscarLayout.setVerticalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBuscarLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel13))
        );

        background.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 390, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(65, 108, 64));
        btnEliminar.setMaximumSize(new java.awt.Dimension(140, 40));
        btnEliminar.setMinimumSize(new java.awt.Dimension(140, 40));
        btnEliminar.setPreferredSize(new java.awt.Dimension(140, 40));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Eliminar");

        javax.swing.GroupLayout btnEliminarLayout = new javax.swing.GroupLayout(btnEliminar);
        btnEliminar.setLayout(btnEliminarLayout);
        btnEliminarLayout.setHorizontalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminarLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel14))
        );
        btnEliminarLayout.setVerticalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminarLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel14))
        );

        background.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 440, -1, -1));

        btnLimpiar.setBackground(new java.awt.Color(65, 108, 64));
        btnLimpiar.setMaximumSize(new java.awt.Dimension(140, 40));
        btnLimpiar.setMinimumSize(new java.awt.Dimension(140, 40));
        btnLimpiar.setPreferredSize(new java.awt.Dimension(140, 40));
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Limpiar");

        javax.swing.GroupLayout btnLimpiarLayout = new javax.swing.GroupLayout(btnLimpiar);
        btnLimpiar.setLayout(btnLimpiarLayout);
        btnLimpiarLayout.setHorizontalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLimpiarLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel15))
        );
        btnLimpiarLayout.setVerticalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLimpiarLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel15))
        );

        background.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 540, -1, -1));

        btnMostrarTodos.setBackground(new java.awt.Color(65, 108, 64));
        btnMostrarTodos.setMaximumSize(new java.awt.Dimension(140, 40));
        btnMostrarTodos.setMinimumSize(new java.awt.Dimension(140, 40));
        btnMostrarTodos.setPreferredSize(new java.awt.Dimension(140, 40));
        btnMostrarTodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarTodosMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Mostrar todos");

        javax.swing.GroupLayout btnMostrarTodosLayout = new javax.swing.GroupLayout(btnMostrarTodos);
        btnMostrarTodos.setLayout(btnMostrarTodosLayout);
        btnMostrarTodosLayout.setHorizontalGroup(
            btnMostrarTodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMostrarTodosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel16))
        );
        btnMostrarTodosLayout.setVerticalGroup(
            btnMostrarTodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMostrarTodosLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel16))
        );

        background.add(btnMostrarTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 590, -1, -1));

        txtIdMatch.setBackground(new java.awt.Color(255, 255, 255));
        txtIdMatch.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtIdMatch.setBorder(null);
        txtIdMatch.setMinimumSize(new java.awt.Dimension(300, 26));
        txtIdMatch.setPreferredSize(new java.awt.Dimension(300, 26));
        background.add(txtIdMatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("ID de Partido:");
        jLabel3.setMaximumSize(new java.awt.Dimension(101, 15));
        jLabel3.setMinimumSize(new java.awt.Dimension(101, 15));
        jLabel3.setPreferredSize(new java.awt.Dimension(101, 15));
        background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jSeparator7.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator7.setMaximumSize(new java.awt.Dimension(300, 10));
        jSeparator7.setMinimumSize(new java.awt.Dimension(300, 10));
        jSeparator7.setPreferredSize(new java.awt.Dimension(300, 10));
        background.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        txtQuanti.setBackground(new java.awt.Color(255, 255, 255));
        txtQuanti.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtQuanti.setBorder(null);
        txtQuanti.setMinimumSize(new java.awt.Dimension(300, 26));
        txtQuanti.setPreferredSize(new java.awt.Dimension(300, 26));
        background.add(txtQuanti, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jSeparator8.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator8.setMaximumSize(new java.awt.Dimension(300, 10));
        jSeparator8.setMinimumSize(new java.awt.Dimension(300, 10));
        jSeparator8.setPreferredSize(new java.awt.Dimension(300, 10));
        background.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Cantidad:");
        jLabel4.setMaximumSize(new java.awt.Dimension(101, 15));
        jLabel4.setMinimumSize(new java.awt.Dimension(101, 15));
        jLabel4.setPreferredSize(new java.awt.Dimension(101, 15));
        background.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        txtPrice.setBackground(new java.awt.Color(255, 255, 255));
        txtPrice.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtPrice.setBorder(null);
        txtPrice.setMinimumSize(new java.awt.Dimension(300, 26));
        txtPrice.setPreferredSize(new java.awt.Dimension(300, 26));
        background.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        jSeparator9.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator9.setMaximumSize(new java.awt.Dimension(300, 10));
        jSeparator9.setMinimumSize(new java.awt.Dimension(300, 10));
        jSeparator9.setPreferredSize(new java.awt.Dimension(300, 10));
        background.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Precio Unitario:");
        jLabel5.setMaximumSize(new java.awt.Dimension(101, 15));
        jLabel5.setMinimumSize(new java.awt.Dimension(101, 15));
        jLabel5.setPreferredSize(new java.awt.Dimension(101, 15));
        background.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("ID de Inventario:");
        jLabel6.setMaximumSize(new java.awt.Dimension(101, 15));
        jLabel6.setMinimumSize(new java.awt.Dimension(101, 15));
        jLabel6.setPreferredSize(new java.awt.Dimension(101, 15));
        background.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        txtIdInventory.setBackground(new java.awt.Color(255, 255, 255));
        txtIdInventory.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtIdInventory.setBorder(null);
        txtIdInventory.setMinimumSize(new java.awt.Dimension(300, 26));
        txtIdInventory.setPreferredSize(new java.awt.Dimension(300, 26));
        background.add(txtIdInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        jSeparator10.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator10.setMaximumSize(new java.awt.Dimension(300, 10));
        jSeparator10.setMinimumSize(new java.awt.Dimension(300, 10));
        jSeparator10.setPreferredSize(new java.awt.Dimension(300, 10));
        background.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseClicked
        try {
            int idVenta = Integer.parseInt(txtIdSale.getText().trim());
            int idLocal = Integer.parseInt(txtIdPlace.getText().trim());
            int idPartido = Integer.parseInt(txtIdMatch.getText().trim());
            int idInventory = Integer.parseInt(txtIdInventory.getText().trim());
            int cantidad = Integer.parseInt(txtQuanti.getText().trim());
            double precioUnitario = Double.parseDouble(txtPrice.getText().trim());

            Sales_Details data = new Sales_Details();
            data.setId_venta(idVenta);
            data.setId_localidad(idLocal);
            data.setId_partido(idPartido);
            data.setId_inventario(idInventory);
            data.setCantidad(cantidad);
            data.setPrecio_unitario(precioUnitario);

            Sales_DetailsService service = new Sales_DetailsService();
            String mensaje = service.create(data);

            if (mensaje.toLowerCase().contains("finalizado")) {
                JOptionPane.showMessageDialog(this, "No se pueden vender boletos para este partido: " + mensaje);
                return;
            }

            JOptionPane.showMessageDialog(this, mensaje);
            updateTable();
            cleanCampos();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Cantidad, IDs y Precio deben ser válidos");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al agregar Info: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCrearMouseClicked

    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
        try {
            int id = Integer.parseInt(txtId.getText().trim());
            Sales_Details data = new Sales_Details();
            data.setId_venta(Integer.parseInt(txtIdSale.getText()));
            data.setId_localidad(Integer.parseInt(txtIdPlace.getText()));
            data.setId_partido(Integer.parseInt(txtIdMatch.getText()));
            data.setId_inventario(Integer.parseInt(txtIdInventory.getText()));
            data.setCantidad(Integer.parseInt(txtQuanti.getText()));
            data.setPrecio_unitario(Double.parseDouble(txtPrice.getText()));

            String mensaje = service.update(id, data);

            if (mensaje.toLowerCase().contains("finalizado")) {
                JOptionPane.showMessageDialog(this, "No se pueden actualizar boletos para este partido: " + mensaje);
                return;
            }

            JOptionPane.showMessageDialog(this, mensaje);
            updateTable();
            cleanCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar Info: " + e.getMessage());
        }
    }//GEN-LAST:event_btnActualizarMouseClicked

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        try {
            int id = Integer.parseInt(txtId.getText().trim());
            modelo.setRowCount(0); // Limpiar tabla

            Sales_Details t = service.getOne(id);
            if (t != null) {
                modelo.addRow(new Object[]{
                    t.getId_detalle(),
                    t.getId_venta(),
                    t.getId_localidad(),
                    t.getId_partido(),
                    t.getId_inventario(),
                    t.getCantidad(),
                    t.getPrecio_unitario()
                });
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró un Info con ID " + id);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un ID válido");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al buscar Info: " + e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        try {
            int id = Integer.parseInt(txtId.getText());
            String mensaje = service.delete(id);
            JOptionPane.showMessageDialog(this, mensaje);
            updateTable();
            cleanCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar Info: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked
        cleanCampos();
    }//GEN-LAST:event_btnLimpiarMouseClicked

    private void btnMostrarTodosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarTodosMouseClicked
        updateTable();
    }//GEN-LAST:event_btnMostrarTodosMouseClicked

private void cleanCampos() {
    txtId.setText("");
    txtIdSale.setText("");
    txtIdPlace.setText("");
    txtIdMatch.setText("");
    txtIdInventory.setText("");
    txtQuanti.setText("");
    txtPrice.setText("");

}

private void updateTable() {
    modelo.setRowCount(0);
    try {
        List<Sales_Details> data = service.getAll();
        for (Sales_Details t : data) {
            modelo.addRow(new Object[]{
                t.getId_detalle(),
                t.getId_venta(),
                t.getId_localidad(),
                t.getId_partido(),
                t.getId_inventario(),
                t.getCantidad(),
                t.getPrecio_unitario()
            });
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar tabla: " + e.getMessage());
    }
}

// <editor-fold defaultstate="collapsed" desc="Declaración de Variables">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel btnActualizar;
    private javax.swing.JPanel btnBuscar;
    private javax.swing.JPanel btnCrear;
    private javax.swing.JPanel btnEliminar;
    private javax.swing.JPanel btnLimpiar;
    private javax.swing.JPanel btnMostrarTodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdInventory;
    private javax.swing.JTextField txtIdMatch;
    private javax.swing.JTextField txtIdPlace;
    private javax.swing.JTextField txtIdSale;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuanti;
    // End of variables declaration//GEN-END:variables
// </editor-fold>

}
