/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.umg.proyectofinalboletos.view;

/**
 *
 * @author MK
 */
public class Initial_Internal_Frame extends javax.swing.JInternalFrame {

    /**
     * Creates new form Init
     */
    public Initial_Internal_Frame() {
        initComponents();
        this.setBorder(null);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Welcome = new javax.swing.JLabel();
        Descr_1 = new javax.swing.JLabel();
        Descr_2 = new javax.swing.JLabel();
        Descr_3 = new javax.swing.JLabel();
        Descr_4 = new javax.swing.JLabel();
        Gest_Empl = new javax.swing.JLabel();
        Gest_Prod = new javax.swing.JLabel();
        Gest_Prov = new javax.swing.JLabel();
        Gest_Client = new javax.swing.JLabel();
        Fact = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1030, 750));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1030, 750));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Welcome.setBackground(new java.awt.Color(0, 0, 0));
        Welcome.setFont(new java.awt.Font("Roboto Medium", 0, 78)); // NOI18N
        Welcome.setForeground(new java.awt.Color(65, 108, 64));
        Welcome.setText("Bienvenido");
        jPanel1.add(Welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        Descr_1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Descr_1.setForeground(new java.awt.Color(0, 0, 0));
        Descr_1.setText("Sistema de Gestion de Partidos. Controla,");
        jPanel1.add(Descr_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        Descr_2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Descr_2.setForeground(new java.awt.Color(0, 0, 0));
        Descr_2.setText("administre y venda de forma eficiente y simple");
        jPanel1.add(Descr_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        Descr_3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Descr_3.setForeground(new java.awt.Color(0, 0, 0));
        Descr_3.setText("Este sistema le permitira mejorar el control de forma detallada y consisa de su negocio.");
        jPanel1.add(Descr_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, 20));

        Descr_4.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Descr_4.setForeground(new java.awt.Color(0, 0, 0));
        Descr_4.setText("Podrá acceder a las diversas herramientas para sus necesidades especificas, tales:");
        jPanel1.add(Descr_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, 20));

        Gest_Empl.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        Gest_Empl.setForeground(new java.awt.Color(0, 0, 0));
        Gest_Empl.setText("• Gestion de Usuarios.");
        jPanel1.add(Gest_Empl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, 20));

        Gest_Prod.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        Gest_Prod.setForeground(new java.awt.Color(0, 0, 0));
        Gest_Prod.setText("• Gestion de Partidos.");
        jPanel1.add(Gest_Prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, 20));

        Gest_Prov.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        Gest_Prov.setForeground(new java.awt.Color(0, 0, 0));
        Gest_Prov.setText("• Gestion de Localidades.");
        jPanel1.add(Gest_Prov, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, 20));

        Gest_Client.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        Gest_Client.setForeground(new java.awt.Color(0, 0, 0));
        Gest_Client.setText("• Gestion de Ventas.");
        jPanel1.add(Gest_Client, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, 20));

        Fact.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        Fact.setForeground(new java.awt.Color(0, 0, 0));
        Fact.setText("• Inventarios.");
        jPanel1.add(Fact, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Descr_1;
    private javax.swing.JLabel Descr_2;
    private javax.swing.JLabel Descr_3;
    private javax.swing.JLabel Descr_4;
    private javax.swing.JLabel Fact;
    private javax.swing.JLabel Gest_Client;
    private javax.swing.JLabel Gest_Empl;
    private javax.swing.JLabel Gest_Prod;
    private javax.swing.JLabel Gest_Prov;
    private javax.swing.JLabel Welcome;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
